modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="${issue_tracker}"
license="${license}"

[[mods]]
  modId="${modid}"
  displayName="${display_name}"
  description="${description}"
  version="${version}"
  displayURL="${display_url}"
  updateJSONURL="${update_url}"
  authors="${authors}"
  credits="${credits}"
  itemIcon="survivalistessentials:rock_stone"
  logoFile="${logo_file}"

[[dependencies.survivalistessentials]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="fruittrees"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="quark"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="biomesoplenty"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="allyoucaneat"
    mandatory=false
    versionRange="[0,]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="watersource"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="sushigocrafting"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="botania"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="immersiveengineering"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="ars_nouveau"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="geckolib3"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="undergarden"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="byg"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="twilightforest"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="ecologics"
    mandatory=false
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
