modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
  modId="${mod_id}"
  displayName="${mod_name}"
  description='''${mod_description}'''
  version="${version}"
  displayURL="${mod_url}"
  updateJSONURL="https://raw.githubusercontent.com/wendall911/Homeostatic/${mod_update_branch}/files/updates.json"
  authors="${mod_author}"
  credits="${mod_credits}"
  itemIcon="survivalistessentials:rock_stone"
  logoFile="${logo_file}"
[[mixins]]
    config = "${mod_id}.mixins.json"
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_loader_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${neoforge_mc_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="fruitfulfun"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="quark"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="biomesoplenty"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="allyoucaneat"
    type="optional"
    versionRange="[0,]"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="watersource"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="sushigocrafting"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="botania"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="immersiveengineering"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="ars_nouveau"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="geckolib3"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="undergarden"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="byg"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="twilightforest"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="ecologics"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="aquaculture"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="malum"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.survivalistessentials]]
    modId="iceandfire"
    type="optional"
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
